//Names: https://www.youtube.com/watch?v=oymWAeqv_-c

module.exports = [
    {
    name: 'Sleve McDichael',
    number: '45',
    img: 'https://i.imgur.com/qh7A0Jh.png',
    position: 'SP',
    hands: 'R/R',
    height: `6'4"`,
    weight: 195,
    contract: true,
    years: 4,
    salary: '25,000,000',
    tags: ['workhorse', 'ace', 'high velocity',],
    starter: true,
    },
    {
    name: 'Onson Sweemey',
    number: '37',
    img: 'https://i.imgur.com/XMu1Xyv.png',
    position: 'C',
    hands: 'R/R',
    height: `6'1"`,
    weight: 220,
    contract: true,
    years: 6,
    salary: '7,000,000',
    tags: ['framing', 'blocking', 'contact hitter'],
    starter: true,
    },
    {
    name: 'Darryl Archideld',
    number: '16',
    img: 'https://i.imgur.com/sGiFkQv.png',
    position: '1B',
    hands: 'L/R',
    height: `6'2"`,
    weight: 210,
    contract: true,
    years: 3,
    salary: '4,000,000',
    tags: ['power hitter', 'iron glove', 'slow', 'strikeouts'],
    starter: true,
    },
    {
    name: 'Anatoli Smorin',
    number: '6',
    img: 'https://i.imgur.com/UIS7KiX.png',
    position: '2B',
    hands: 'L/R',
    height: `6'0"`,
    weight: 185,
    contract: true,
    years: 5,
    salary: '12,000,000',
    tags: ['contact hitter', 'gold glove', 'base stealer'],
    starter: true,
    },
    {
    name: 'Glenallen Mixon',
    number: '55',
    img: 'https://i.imgur.com/uXF5fZK.png',
    position: '3B',
    hands: 'R/R',
    height: `6'4"`,
    weight: 205,
    contract: true,
    years: 8,
    salary: '28,000,000',
    tags: ['contact hitter', 'good eye', 'power hitter', 'MVP'],
    starter: true,
    },
    {
    name: 'Rey McScriff',
    number: '26',
    img: 'https://i.imgur.com/Ps5f3XC.png',
    position: 'SS',
    hands: 'S/R',
    height: `5'11"`,
    weight: 180,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['contact hitter', 'clutch', 'batting title', 'MVP'],
    starter: false,
    },
    {
    name: 'Raul Chamgerlain',
    number: '79',
    img: 'https://i.imgur.com/gDvVlmn.png',
    position: 'LF',
    hands: 'L/R',
    height: `6'3"`,
    weight: 230,
    contract: true,
    years: 3,
    salary: '11,000,000',
    tags: ['power hitter', 'slow', 'silver slugger', 'clutch'],
    starter: true,
    },
    {
    name: 'Bobson Dugnutt',
    number: '9',
    img: 'https://i.imgur.com/kaKlOTt.png',
    position: 'CF',
    hands: 'L/R',
    height: `6'2"`,
    weight: 195,
    contract: true,
    years: 5,
    salary: '13,000,000',
    tags: ['slap hitter', 'gold glove', 'good eye', 'base stealer', 'range'],
    starter: true,
    },
    {
    name: 'Coll Bitzron',
    number: '63',
    img: 'https://i.imgur.com/eX3fA7S.png',
    position: 'RF',
    hands: 'R/R',
    height: `6'4"`,
    weight: 205,
    contract: true,
    years: 5,
    salary: '10,000,000',
    tags: ['opposite field approach', 'cannon', 'range'],
    starter: true,
    },
    {
    name: 'Mario McRlwain',
    number: '41',
    img: 'https://i.imgur.com/3QKaQAs.png',
    position: 'CP',
    hands: 'L/L',
    height: `6'1"`,
    weight: 240,
    contract: true,
    years: 2,
    salary: '13,000,000',
    tags: ['closer', 'clutch', 'strikeouts', 'wipeout slider',],
    starter: false,
    },
    {
    name: 'Kevin Nogilny',
    number: '29',
    img: 'https://i.imgur.com/lsMUi5G.png',
    position: 'SP',
    hands: 'L/R',
    height: `5'10"`,
    weight: 170,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['#2 starter', 'innings eater', 'control pitcher', 'changeup'],
    starter: false,
    },
    {
    name: 'Tony Smehrik',
    number: '22',
    img: 'https://i.imgur.com/2TKo0Ya.png',
    position: 'SP',
    hands: 'R/L',
    height: `6'6"`,
    weight: 220,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['mid-rotation', 'high velocity', 'control issues', 'low stamina'],
    starter: false,
    },
    {
    name: 'Willie Dustice',
    number: '38',
    img: 'https://i.imgur.com/q9SrF7V.png',
    position: 'LF',
    hands: 'L/R',
    height: `6'2"`,
    weight: 195,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['power hitter', 'low average', 'range', 'cannon'],
    starter: false,
    },
    {
    name: 'Jeromy Gride',
    number: '18',
    img: 'https://i.imgur.com/O5wykjQ.png',
    position: '1B',
    hands: 'L/L',
    height: `6'3"`,
    weight: 215,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['contact hitter', 'gold glove', 'range', 'cannon'],
    starter: false,
    },
    {
    name: 'Scott Dourque',
    number: '3',
    img: 'https://i.imgur.com/Dkl9S1l.png',
    position: '3B',
    hands: 'S/R',
    height: `6'5"`,
    weight: 170,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['low average', 'low power', 'gold glove', 'range', 'cannon', 'defensive replacement'],
    starter: false,
    },
    {
    name: 'Dean Wesrey',
    number: '56',
    img: 'https://i.imgur.com/SwwCNO8.png',
    position: '2B',
    hands: 'L/R',
    height: `6'0"`,
    weight: 270,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['low average', 'high power', 'iron glove', 'slow', 'platoon'],
    starter: false,
    },
    {
    name: 'Mike Truk',
    number: '31',
    img: 'https://i.imgur.com/0M14ZIc.png',
    position: '1B',
    hands: 'R/R',
    height: `6'5"`,
    weight: 310,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['low average', 'high power', 'slow', 'pinch hitter', 'pull hitter'],
    starter: false,
    },
    {
    name: 'Dwigt Rortugal',
    number: '44',
    img: 'https://i.imgur.com/PmY6JyA.png',
    position: 'RF',
    hands: 'L/L',
    height: `6'2"`,
    weight: 200,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['league average', '4th OF', 'pinch hitter'],
    starter: false,
    },
    {
    name: 'Tim Sandaele',
    number: '9',
    img: 'https://i.imgur.com/5nDiRiF.png',
    position: 'C',
    hands: 'R/R',
    height: `6'0"`,
    weight: 250,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['low average', 'slow', 'blocking'],
    starter: false,
    },
    {
    name: 'Karl Dandleton',
    number: '51',
    img: 'https://i.imgur.com/LwIOMQF.png',
    position: 'CP',
    hands: 'R/R',
    height: `5'10"`,
    weight: 200,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['high velocity', 'wild', 'strikeouts'],
    starter: false,
    },
    {
    name: 'Mike Sernandez',
    number: '99',
    img: 'https://i.imgur.com/rYL6mlh.png',
    position: 'SP',
    hands: 'R/L',
    height: `6'1"`,
    weight: 210,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['fifth starter', 'innings eater', 'pitched to contact'],
    starter: false,
    },
    {
    name: 'Todd Bonzalez',
    number: '17',
    img: 'https://i.imgur.com/AHhw3pD.png',
    position: 'SP',
    hands: 'L/R',
    height: `6'0"`,
    weight: 190,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['fifth starter', 'low stamina', 'strikeouts'],
    starter: false,
    },
    {
    name: 'Jon Dowd',
    number: '51',
    img: 'https://i.imgur.com/Mmaqbk9.png',
    position: 'LF',
    hands: 'L/L',
    height: `6'1"`,
    weight: 230,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['home run champion', 'plate discipline', 'MVP'],
    starter: false,
    },
    {
    name: 'Reggie Stocker',
    number: '51',
    img: 'https://i.imgur.com/Kc9iNA6.png',
    position: 'LF',
    hands: 'L/L',
    height: `6'1"`,
    weight: 230,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['home run champion', 'plate discipline', 'MVP'],
    starter: false,
    },
    {
    name: 'Gin Ginlonz',
    number: '16',
    img: 'https://i.imgur.com/yotH48H.png',
    position: 'SS',
    hands: 'L/R',
    height: `6'2"`,
    weight: 199,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['cannon', 'low range', 'league average hitter'],
    starter: false,
    },
    {
    name: 'Dony Olerberz',
    number: '33',
    img: 'https://i.imgur.com/wSX5bDe.png',
    position: '2B',
    hands: 'L/L',
    height: `6'1"`,
    weight: 210,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['high average', 'low range', 'wild arm'],
    starter: false,
    },
    {
    name: 'Cloyd Zlydaszyk',
    number: '50',
    img: 'https://i.imgur.com/H0yphcF.png',
    position: 'CF',
    hands: 'R/R',
    height: `6'4"`,
    weight: 220,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['high average', 'power hitter', 'poor speed'],
    starter: false,
    },
    {
    name: 'Yans Loovensan',
    number: '5',
    img: 'https://i.imgur.com/G7D2s3z.png',
    position: 'C',
    hands: 'L/R',
    height: `6'0"`,
    weight: 230,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['poor speed', 'low average hitter', 'low power', 'elite framer'],
    starter: false,
    },
    {
    name: 'Lood Janglosti',
    number: '20',
    img: 'https://i.imgur.com/Yo1dP45.png',
    position: 'SS',
    hands: 'L/L',
    height: `6'1"`,
    weight: 200,
    contract: false,
    years: 0,
    salary: '0',
    tags: ['base stealer', 'defensive replacement', 'low power', 'wild arm'],
    starter: false,
    },
]